name: Build ZMK firmware
on: [workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      archive_name: firmware-${{ github.ref_name }}-${{ substring(github.event.repository.updated_at, 0, 10) }}-${{ github.run_number }}.zip